#deploying a simple Django backend application
name: Deploy Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /opt/django-app/django27-05-2026M/django_school

            git pull origin main
 
            source ../venv/bin/activate

            pip install -r requirements.txt

            python manage.py migrate --noinput
