name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "Starting deployment..."

            cd /opt/django-app/django27-05-2026M

            git pull origin main

            cd django_school

            source ../venv/bin/activate

            pip install -r requirements.txt

            python manage.py migrate --noinput

            python manage.py collectstatic --noinput || true

            pkill -f gunicorn || true

            nohup gunicorn django_school.wsgi:application \
              --bind 127.0.0.1:8000 \
              --daemon

            echo "Deployment completed successfully."
